spring.datasource.url: jdbc:mysql://seralock-db.cwhxcgdndstk.us-east-2.rds.amazonaws.com:3306/seralock_db_dev
spring.datasource.username: dbdev
spring.datasource.password: Dbdev@Enfec13
spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
#60 sec
spring.datasource.hikari.connection-timeout: 60000
# max 5
spring.datasource.hikari.maximum-pool-size: 10